//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LikeMovies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminMovie
    {
        public int AdminID { get; set; }
        public string NameAd { get; set; }
        public string Email { get; set; }
        public string UsernameAd { get; set; }
        public string PasswordAd { get; set; }
        public string AvartarURL { get; set; }
    }
}
