//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LikeMovies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountCodes
    {
        public int DiscountID { get; set; }
        public Nullable<int> PlanID { get; set; }
        public string DiscountCode { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual SubscriptionPlans SubscriptionPlans { get; set; }
    }
}
