//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LikeMovies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Episodes
    {
        public int EpisodeID { get; set; }
        public int SeasonID { get; set; }
        public int EpisodeNumber { get; set; }
        public string Title { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string VideoURL { get; set; }
    
        public virtual Seasons Seasons { get; set; }
    }
}
