//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LikeMovies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosterMovie
    {
        public int PosterID { get; set; }
        public Nullable<int> MovieID { get; set; }
        public string PosterURL { get; set; }
        public Nullable<bool> IsSlider { get; set; }
        public Nullable<int> SliderOrder { get; set; }
    
        public virtual Movies Movies { get; set; }
    }
}
