//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LikeMovies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seasons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seasons()
        {
            this.Episodes = new HashSet<Episodes>();
        }
    
        public int SeasonID { get; set; }
        public int MovieID { get; set; }
        public int SeasonNumber { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<int> TotalEpisodes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Episodes> Episodes { get; set; }
        public virtual Movies Movies { get; set; }
    }
}
